//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.25 at 05:01:25 PM IST 
//


package org.gleif.data.schema.leidata._2016;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EntityCategoryTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="EntityCategoryTypeEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="GENERAL"/&gt;
 *     &lt;enumeration value="BRANCH"/&gt;
 *     &lt;enumeration value="FUND"/&gt;
 *     &lt;enumeration value="SOLE_PROPRIETOR"/&gt;
 *     &lt;enumeration value="RESIDENT_GOVERNMENT_ENTITY"/&gt;
 *     &lt;enumeration value="INTERNATIONAL_ORGANIZATION"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "EntityCategoryTypeEnum")
@XmlEnum
public enum EntityCategoryTypeEnum {


    /**
     * The legal entity is a general legal entity.
     * 
     */
    GENERAL,

    /**
     * The legal entity is a branch of another legal entity.
     * 
     */
    BRANCH,

    /**
     * The legal entity is an investment fund defined as a collective investment scheme (or pooled investment) beneficially owned by multiple investors and managed on behalf of those investors by an asset manager or by the fund itself.
     * 
     */
    FUND,

    /**
     * The legal entity is an individual acting in a business
     *             capacity.
     * 
     */
    SOLE_PROPRIETOR,

    /**
     * The legal entity is a non-market producer, part of a central, state or local government, social security funds or a non-profit institution (NPI) controlled by government units.
     * 
     */
    RESIDENT_GOVERNMENT_ENTITY,

    /**
     * The legal entity is a non-resident unit created by international agreements or other arrangements for the provision of non-market services or financial intermediation at the international level.
     * 
     */
    INTERNATIONAL_ORGANIZATION;

    public String value() {
        return name();
    }

    public static EntityCategoryTypeEnum fromValue(String v) {
        return valueOf(v);
    }

}
