//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.25 at 05:01:25 PM IST 
//


package org.gleif.data.schema.leidata._2016;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LegalEntityEventGroupTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="LegalEntityEventGroupTypeEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="REVERSE_TAKEOVER"/&gt;
 *     &lt;enumeration value="STANDALONE"/&gt;
 *     &lt;enumeration value="CHANGE_LEGAL_FORM_AND_NAME"/&gt;
 *     &lt;enumeration value="COMPLEX_CHANGE_LEGAL_FORM"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "LegalEntityEventGroupTypeEnum")
@XmlEnum
public enum LegalEntityEventGroupTypeEnum {


    /**
     * This event is part of a reverse takeover event.
     * 
     */
    REVERSE_TAKEOVER,

    /**
     * Single / standalone legal entity event with no combination of multiple events.
     * 
     */
    STANDALONE,

    /**
     * legal entity event including change of the legal name triggered by change of the legal form.
     * 
     */
    CHANGE_LEGAL_FORM_AND_NAME,

    /**
     * legal entity event including change of the legal entity status triggered by change of the legal form.
     * 
     */
    COMPLEX_CHANGE_LEGAL_FORM;

    public String value() {
        return name();
    }

    public static LegalEntityEventGroupTypeEnum fromValue(String v) {
        return valueOf(v);
    }

}
