//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.25 at 05:01:25 PM IST 
//


package org.gleif.data.schema.leidata._2016;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.gleif.data.schema.leidata._2016 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.gleif.data.schema.leidata._2016
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AffectedFieldsType }
     * 
     */
    public AffectedFieldsType createAffectedFieldsType() {
        return new AffectedFieldsType();
    }

    /**
     * Create an instance of {@link LEIData }
     * 
     */
    public LEIData createLEIData() {
        return new LEIData();
    }

    /**
     * Create an instance of {@link LEIHeaderType }
     * 
     */
    public LEIHeaderType createLEIHeaderType() {
        return new LEIHeaderType();
    }

    /**
     * Create an instance of {@link LEIRecordsType }
     * 
     */
    public LEIRecordsType createLEIRecordsType() {
        return new LEIRecordsType();
    }

    /**
     * Create an instance of {@link LEIRecordType }
     * 
     */
    public LEIRecordType createLEIRecordType() {
        return new LEIRecordType();
    }

    /**
     * Create an instance of {@link EntityType }
     * 
     */
    public EntityType createEntityType() {
        return new EntityType();
    }

    /**
     * Create an instance of {@link RegistrationType }
     * 
     */
    public RegistrationType createRegistrationType() {
        return new RegistrationType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link TransliteratedAddressType }
     * 
     */
    public TransliteratedAddressType createTransliteratedAddressType() {
        return new TransliteratedAddressType();
    }

    /**
     * Create an instance of {@link AssociatedEntityType }
     * 
     */
    public AssociatedEntityType createAssociatedEntityType() {
        return new AssociatedEntityType();
    }

    /**
     * Create an instance of {@link RegistrationAuthorityType }
     * 
     */
    public RegistrationAuthorityType createRegistrationAuthorityType() {
        return new RegistrationAuthorityType();
    }

    /**
     * Create an instance of {@link OtherValidationAuthoritiesType }
     * 
     */
    public OtherValidationAuthoritiesType createOtherValidationAuthoritiesType() {
        return new OtherValidationAuthoritiesType();
    }

    /**
     * Create an instance of {@link ValidationAuthorityType }
     * 
     */
    public ValidationAuthorityType createValidationAuthorityType() {
        return new ValidationAuthorityType();
    }

    /**
     * Create an instance of {@link OtherAddressType }
     * 
     */
    public OtherAddressType createOtherAddressType() {
        return new OtherAddressType();
    }

    /**
     * Create an instance of {@link OtherAddressesType }
     * 
     */
    public OtherAddressesType createOtherAddressesType() {
        return new OtherAddressesType();
    }

    /**
     * Create an instance of {@link TransliteratedOtherAddressesType }
     * 
     */
    public TransliteratedOtherAddressesType createTransliteratedOtherAddressesType() {
        return new TransliteratedOtherAddressesType();
    }

    /**
     * Create an instance of {@link TransliteratedOtherAddressType }
     * 
     */
    public TransliteratedOtherAddressType createTransliteratedOtherAddressType() {
        return new TransliteratedOtherAddressType();
    }

    /**
     * Create an instance of {@link OtherEntityNamesType }
     * 
     */
    public OtherEntityNamesType createOtherEntityNamesType() {
        return new OtherEntityNamesType();
    }

    /**
     * Create an instance of {@link TransliteratedOtherEntityNamesType }
     * 
     */
    public TransliteratedOtherEntityNamesType createTransliteratedOtherEntityNamesType() {
        return new TransliteratedOtherEntityNamesType();
    }

    /**
     * Create an instance of {@link OtherEntityNameType }
     * 
     */
    public OtherEntityNameType createOtherEntityNameType() {
        return new OtherEntityNameType();
    }

    /**
     * Create an instance of {@link SuccessorEntityType }
     * 
     */
    public SuccessorEntityType createSuccessorEntityType() {
        return new SuccessorEntityType();
    }

    /**
     * Create an instance of {@link LegalFormType }
     * 
     */
    public LegalFormType createLegalFormType() {
        return new LegalFormType();
    }

    /**
     * Create an instance of {@link NameType }
     * 
     */
    public NameType createNameType() {
        return new NameType();
    }

    /**
     * Create an instance of {@link TransliteratedOtherEntityNameType }
     * 
     */
    public TransliteratedOtherEntityNameType createTransliteratedOtherEntityNameType() {
        return new TransliteratedOtherEntityNameType();
    }

    /**
     * Create an instance of {@link TransliteratedNameType }
     * 
     */
    public TransliteratedNameType createTransliteratedNameType() {
        return new TransliteratedNameType();
    }

    /**
     * Create an instance of {@link LegalEntityEventsType }
     * 
     */
    public LegalEntityEventsType createLegalEntityEventsType() {
        return new LegalEntityEventsType();
    }

    /**
     * Create an instance of {@link LegalEntityEventContainerType }
     * 
     */
    public LegalEntityEventContainerType createLegalEntityEventContainerType() {
        return new LegalEntityEventContainerType();
    }

    /**
     * Create an instance of {@link AffectedFieldsType.AffectedField }
     * 
     */
    public AffectedFieldsType.AffectedField createAffectedFieldsTypeAffectedField() {
        return new AffectedFieldsType.AffectedField();
    }

}
