//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.25 at 05:01:25 PM IST 
//


package org.gleif.data.schema.leidata._2016;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SuccessorEntityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SuccessorEntityType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="SuccessorLEI" type="{http://www.gleif.org/data/schema/leidata/2016}LEIType"/&gt;
 *         &lt;element name="SuccessorEntityName" type="{http://www.gleif.org/data/schema/leidata/2016}NameType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SuccessorEntityType", propOrder = {
    "successorEntityName",
    "successorLEI"
})
public class SuccessorEntityType
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(name = "SuccessorEntityName")
    protected NameType successorEntityName;
    @XmlElement(name = "SuccessorLEI")
    protected String successorLEI;

    /**
     * Gets the value of the successorEntityName property.
     * 
     * @return
     *     possible object is
     *     {@link NameType }
     *     
     */
    public NameType getSuccessorEntityName() {
        return successorEntityName;
    }

    /**
     * Sets the value of the successorEntityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameType }
     *     
     */
    public void setSuccessorEntityName(NameType value) {
        this.successorEntityName = value;
    }

    /**
     * Gets the value of the successorLEI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuccessorLEI() {
        return successorLEI;
    }

    /**
     * Sets the value of the successorLEI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuccessorLEI(String value) {
        this.successorLEI = value;
    }

}
