//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.13 at 06:32:38 PM IST 
//


package org.gleif.data.schema.leidata._2016;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AssociatedEntityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssociatedEntityType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="AssociatedLEI" type="{http://www.gleif.org/data/schema/leidata/2016}LEIType"/&gt;
 *         &lt;element name="AssociatedEntityName" type="{http://www.gleif.org/data/schema/leidata/2016}NameType"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="type" use="required" type="{http://www.gleif.org/data/schema/leidata/2016}AssociatedEntityTypeEnum" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AssociatedEntityType", propOrder = {
    "associatedEntityName",
    "associatedLEI"
})
public class AssociatedEntityType
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(name = "AssociatedEntityName")
    protected NameType associatedEntityName;
    @XmlElement(name = "AssociatedLEI")
    protected String associatedLEI;
    @XmlAttribute(name = "type", required = true)
    protected AssociatedEntityTypeEnum type;

    /**
     * Gets the value of the associatedEntityName property.
     * 
     * @return
     *     possible object is
     *     {@link NameType }
     *     
     */
    public NameType getAssociatedEntityName() {
        return associatedEntityName;
    }

    /**
     * Sets the value of the associatedEntityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameType }
     *     
     */
    public void setAssociatedEntityName(NameType value) {
        this.associatedEntityName = value;
    }

    /**
     * Gets the value of the associatedLEI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssociatedLEI() {
        return associatedLEI;
    }

    /**
     * Sets the value of the associatedLEI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssociatedLEI(String value) {
        this.associatedLEI = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link AssociatedEntityTypeEnum }
     *     
     */
    public AssociatedEntityTypeEnum getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssociatedEntityTypeEnum }
     *     
     */
    public void setType(AssociatedEntityTypeEnum value) {
        this.type = value;
    }

}
