//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.14 at 11:28:53 AM IST 
//


package org.gleif.data.schema.leidata._2016;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EntitySubCategoryTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="EntitySubCategoryTypeEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="CENTRAL_GOVERNMENT"/&gt;
 *     &lt;enumeration value="STATE_GOVERNMENT"/&gt;
 *     &lt;enumeration value="LOCAL_GOVERNMENT"/&gt;
 *     &lt;enumeration value="SOCIAL_SECURITY"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "EntitySubCategoryTypeEnum")
@XmlEnum
public enum EntitySubCategoryTypeEnum {


    /**
     * The legal entity is a central government subsector which consists of the institutional units plus non-profit institution (NPI) controlled by the central government institutions.
     * 
     */
    CENTRAL_GOVERNMENT,

    /**
     * The legal entity is a state government subsector which consists of the institutional units that exercise some government functions at a level below that of the central government and above that of the government institutional units existing at a local level.
     * 
     */
    STATE_GOVERNMENT,

    /**
     * The legal entity is a local government subsector which consists of local governments that are separate institutional units.
     * 
     */
    LOCAL_GOVERNMENT,

    /**
     * The legal entity is a social security scheme which covers a wide variety of programmes, providing benefits in cash or in kind for old age, invalidity or death, survivors, sickness and maternity, work injury, unemployment, family allowance, health care, etc.
     * 
     */
    SOCIAL_SECURITY;

    public String value() {
        return name();
    }

    public static EntitySubCategoryTypeEnum fromValue(String v) {
        return valueOf(v);
    }

}
