//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.13 at 06:32:38 PM IST 
//


package org.gleif.data.schema.leidata._2016;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LegalEntityEventStatusEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="LegalEntityEventStatusEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="IN_PROGRESS"/&gt;
 *     &lt;enumeration value="WITHDRAWN_CANCELLED"/&gt;
 *     &lt;enumeration value="COMPLETED"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "LegalEntityEventStatusEnum")
@XmlEnum
public enum LegalEntityEventStatusEnum {


    /**
     * The legal entity event activity and processing is in progress.
     * 
     */
    IN_PROGRESS,

    /**
     * The legal entity event as announced will not occur.
     * 
     */
    WITHDRAWN_CANCELLED,

    /**
     * The legal entity event activity and processing have been completed as of the LegalEntityEventEffectiveDate.
     * 
     */
    COMPLETED;

    public String value() {
        return name();
    }

    public static LegalEntityEventStatusEnum fromValue(String v) {
        return valueOf(v);
    }

}
