//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.13 at 06:32:38 PM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.gleif.org/data/schema/leidata/2016", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.gleif.data.schema.leidata._2016;
