//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.13 at 06:32:38 PM IST 
//


package org.gleif.data.schema.leidata._2016;

import java.io.Serializable;
import java.util.Calendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3._2001.xmlschema.Adapter1;


/**
 * <p>Java class for RegistrationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegistrationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="InitialRegistrationDate" type="{http://www.gleif.org/data/schema/leidata/2016}LEIDateTimeProfile"/&gt;
 *         &lt;element name="LastUpdateDate" type="{http://www.gleif.org/data/schema/leidata/2016}LEIDateTimeProfile"/&gt;
 *         &lt;element name="RegistrationStatus" type="{http://www.gleif.org/data/schema/leidata/2016}RegistrationStatusEnum"/&gt;
 *         &lt;element name="NextRenewalDate" type="{http://www.gleif.org/data/schema/leidata/2016}LEIDateTimeProfile"/&gt;
 *         &lt;element name="ManagingLOU" type="{http://www.gleif.org/data/schema/leidata/2016}LEIType"/&gt;
 *         &lt;element name="ValidationSources" type="{http://www.gleif.org/data/schema/leidata/2016}ValidationSourcesEnum" minOccurs="0"/&gt;
 *         &lt;element name="ValidationAuthority" type="{http://www.gleif.org/data/schema/leidata/2016}ValidationAuthorityType" minOccurs="0"/&gt;
 *         &lt;element name="OtherValidationAuthorities" type="{http://www.gleif.org/data/schema/leidata/2016}OtherValidationAuthoritiesType" minOccurs="0"/&gt;
 *         &lt;element name="NextVersion" type="{http://www.gleif.org/data/schema/leidata/2016}RegistrationNextVersionType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegistrationType", propOrder = {
    "initialRegistrationDate",
    "lastUpdateDate",
    "registrationStatus",
    "nextRenewalDate",
    "managingLOU",
    "validationSources",
    "validationAuthority",
    "otherValidationAuthorities",
    "nextVersion"
})
public class RegistrationType
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(name = "InitialRegistrationDate", required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected Calendar initialRegistrationDate;
    @XmlElement(name = "LastUpdateDate", required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected Calendar lastUpdateDate;
    @XmlElement(name = "RegistrationStatus", required = true)
    @XmlSchemaType(name = "string")
    protected RegistrationStatusEnum registrationStatus;
    @XmlElement(name = "NextRenewalDate", required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected Calendar nextRenewalDate;
    @XmlElement(name = "ManagingLOU", required = true)
    protected String managingLOU;
    @XmlElement(name = "ValidationSources")
    @XmlSchemaType(name = "string")
    protected ValidationSourcesEnum validationSources;
    @XmlElement(name = "ValidationAuthority")
    protected ValidationAuthorityType validationAuthority;
    @XmlElement(name = "OtherValidationAuthorities")
    protected OtherValidationAuthoritiesType otherValidationAuthorities;
    @XmlElement(name = "NextVersion")
    protected RegistrationNextVersionType nextVersion;

    /**
     * Gets the value of the initialRegistrationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getInitialRegistrationDate() {
        return initialRegistrationDate;
    }

    /**
     * Sets the value of the initialRegistrationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitialRegistrationDate(Calendar value) {
        this.initialRegistrationDate = value;
    }

    /**
     * Gets the value of the lastUpdateDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * Sets the value of the lastUpdateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastUpdateDate(Calendar value) {
        this.lastUpdateDate = value;
    }

    /**
     * Gets the value of the registrationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link RegistrationStatusEnum }
     *     
     */
    public RegistrationStatusEnum getRegistrationStatus() {
        return registrationStatus;
    }

    /**
     * Sets the value of the registrationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegistrationStatusEnum }
     *     
     */
    public void setRegistrationStatus(RegistrationStatusEnum value) {
        this.registrationStatus = value;
    }

    /**
     * Gets the value of the nextRenewalDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getNextRenewalDate() {
        return nextRenewalDate;
    }

    /**
     * Sets the value of the nextRenewalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextRenewalDate(Calendar value) {
        this.nextRenewalDate = value;
    }

    /**
     * Gets the value of the managingLOU property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManagingLOU() {
        return managingLOU;
    }

    /**
     * Sets the value of the managingLOU property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManagingLOU(String value) {
        this.managingLOU = value;
    }

    /**
     * Gets the value of the validationSources property.
     * 
     * @return
     *     possible object is
     *     {@link ValidationSourcesEnum }
     *     
     */
    public ValidationSourcesEnum getValidationSources() {
        return validationSources;
    }

    /**
     * Sets the value of the validationSources property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidationSourcesEnum }
     *     
     */
    public void setValidationSources(ValidationSourcesEnum value) {
        this.validationSources = value;
    }

    /**
     * Gets the value of the validationAuthority property.
     * 
     * @return
     *     possible object is
     *     {@link ValidationAuthorityType }
     *     
     */
    public ValidationAuthorityType getValidationAuthority() {
        return validationAuthority;
    }

    /**
     * Sets the value of the validationAuthority property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidationAuthorityType }
     *     
     */
    public void setValidationAuthority(ValidationAuthorityType value) {
        this.validationAuthority = value;
    }

    /**
     * Gets the value of the otherValidationAuthorities property.
     * 
     * @return
     *     possible object is
     *     {@link OtherValidationAuthoritiesType }
     *     
     */
    public OtherValidationAuthoritiesType getOtherValidationAuthorities() {
        return otherValidationAuthorities;
    }

    /**
     * Sets the value of the otherValidationAuthorities property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtherValidationAuthoritiesType }
     *     
     */
    public void setOtherValidationAuthorities(OtherValidationAuthoritiesType value) {
        this.otherValidationAuthorities = value;
    }

    /**
     * Gets the value of the nextVersion property.
     * 
     * @return
     *     possible object is
     *     {@link RegistrationNextVersionType }
     *     
     */
    public RegistrationNextVersionType getNextVersion() {
        return nextVersion;
    }

    /**
     * Sets the value of the nextVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegistrationNextVersionType }
     *     
     */
    public void setNextVersion(RegistrationNextVersionType value) {
        this.nextVersion = value;
    }

}
