//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.13 at 06:32:38 PM IST 
//


package org.gleif.data.schema.leidata._2016;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RegistrationStatusEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="RegistrationStatusEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="PENDING_VALIDATION"/&gt;
 *     &lt;enumeration value="ISSUED"/&gt;
 *     &lt;enumeration value="DUPLICATE"/&gt;
 *     &lt;enumeration value="LAPSED"/&gt;
 *     &lt;enumeration value="MERGED"/&gt;
 *     &lt;enumeration value="RETIRED"/&gt;
 *     &lt;enumeration value="ANNULLED"/&gt;
 *     &lt;enumeration value="CANCELLED"/&gt;
 *     &lt;enumeration value="TRANSFERRED"/&gt;
 *     &lt;enumeration value="PENDING_TRANSFER"/&gt;
 *     &lt;enumeration value="PENDING_ARCHIVAL"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "RegistrationStatusEnum")
@XmlEnum
public enum RegistrationStatusEnum {


    /**
     * An application for an LEI that has been submitted and which is being
     *             processed and validated.
     * 
     */
    PENDING_VALIDATION,

    /**
     * An LEI Registration that has been validated and issued, and which identifies an entity having a legal entity status of ACTIVE as of the Date of First LEI Assignment or the Date of Last Update of the LEI Data Record.
     * 
     */
    ISSUED,

    /**
     * An LEI Registration that has been determined to be a duplicate
     *             registration of the same legal entity as another LEI Registration; the DUPLICATE status
     *             is assigned to the non-surviving registration (i.e. the LEI that should no longer be
     *             used).
     * 
     */
    DUPLICATE,

    /**
     * An LEI registration that has not been renewed by the 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;code xmlns:lei="http://www.gleif.org/data/schema/leidata/2016" xmlns:p159472_="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:p823927_="https://jakarta.ee/xml/ns/jaxb" xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;NextRenewalDate&lt;/code&gt;
     * </pre>
     *  and is not known by public sources to have a legal entity status of INACTIVE.
     * 
     */
    LAPSED,

    /**
     * An LEI registration for an entity that has been merged into another legal entity, such that this legal entity no longer exists as an operating entity. (Deprecated as of LEI-CDF 3.0)
     * 
     */
    MERGED,

    /**
     * An LEI registration status for an entity that has been affected by certain legal entity events.
     * 
     */
    RETIRED,

    /**
     * An LEI registration that was determined to be erroneous or invalid after it was issued.
     * 
     */
    ANNULLED,

    /**
     * An LEI registration that was abandoned prior to issuance of an LEI
     *           
     * 
     */
    CANCELLED,

    /**
     * An LEI registration that has been transferred to a different LOU as the
     *             managing LOU.
     * 
     */
    TRANSFERRED,

    /**
     * An LEI registration that has been requested to be transferred to another
     *             LOU. The request is being processed at the sending LOU
     * 
     */
    PENDING_TRANSFER,

    /**
     * An LEI registration is about to be transferred to a different LOU, after
     *             which its registration status will revert to a non-pending status. 
     * 
     */
    PENDING_ARCHIVAL;

    public String value() {
        return name();
    }

    public static RegistrationStatusEnum fromValue(String v) {
        return valueOf(v);
    }

}
