//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.14 at 11:28:53 AM IST 
//


package org.w3._2001.xmlschema;

import java.util.Date;
import jakarta.xml.bind.annotation.adapters.XmlAdapter;

public class Adapter1
    extends XmlAdapter<String, Date>
{


    public Date unmarshal(String value) {
        return (com.example.demo.parser.JaxbConverter.parseDateTime(value));
    }

    public String marshal(Date value) {
        return (com.example.demo.parser.JaxbConverter.printDateTime(value));
    }

}
